### ISSUE TITLE
generated enum types mismatch when imported

### ISSUE THREAD

**Issue by schphil** [librasn/compiler#68]
When generating rust code for [DSRC-region.asn](https://forge.etsi.org/rep/ITS/asn1/is_ts103301/-/blob/release2/DSRC-region.asn?ref_type=heads) the enums types are suffixed with `_Type`.

```rust
    use core::borrow::Borrow;
    use lazy_static::lazy_static;
    use rasn::prelude::*;
    #[derive(Debug, Clone, PartialEq)]
    pub enum RegAdvisorySpeed_Type {}
    impl RegAdvisorySpeed_Type {
        pub fn decode<D: Decoder>(
            decoder: &mut D,
            open_type_payload: Option<&Any>,
            identifier: &RegionId,
        ) -> Result<Self, D::Error> {
            match identifier {
                _ => Err(rasn::error::DecodeError::from_kind(
                    rasn::error::DecodeErrorKind::Custom {
                        msg: alloc::format!(
                            "Unknown unique identifier for information object class instance."
                        ),
                    },
                    decoder.codec(),
                )
                .into()),
            }
        }
        pub fn encode<E: Encoder>(
            &self,
            encoder: &mut E,
            identifier: &RegionId,
        ) -> Result<(), E::Error> {
            match (self, identifier) {
                _ => Err(rasn::error::EncodeError::from_kind(
                    rasn::error::EncodeErrorKind::Custom {
                        msg: alloc::format!(
                            "Unknown unique identifier for information object class instance."
                        ),
                    },
                    encoder.codec(),
                )
                .into()),
            }
        }
    }
 ```
 
 However when imported in [DRSC.asn](https://forge.etsi.org/rep/ITS/asn1/is_ts103301/-/blob/release2/DSRC.asn?ref_type=heads#L17-L26) the suffix misses:
 
 ```rust
 pub mod etsi__its__dsrc {
    extern crate alloc;
    use super::super::etsi_its_cdd::etsi__its__cdd::{Iso3833VehicleType, Latitude, Longitude, StationID};
    use super::etsi__its__dsrc__region::{
        RegAdvisorySpeed, RegComputedLane, RegConnectionManeuverAssist, RegGenericLane,
        RegIntersectionGeometry, RegIntersectionState, RegLaneAttributes, RegLaneDataAttribute,
        RegMapData, RegMovementEvent, RegMovementState, RegNodeAttributeSetXY,
        RegNodeOffsetPointXY, RegPosition3D, RegRTCMcorrections, RegRequestorDescription,
        RegRequestorType, RegRestrictionUserType, RegRoadSegment, RegSPAT, RegSignalControlZone,
        RegSignalRequest, RegSignalRequestMessage, RegSignalRequestPackage, RegSignalStatus,
        RegSignalStatusMessage, RegSignalStatusPackage,
    };
```

**Comment by Rawk** [comment]
Looks like this is fixed. There is no longer any types with the suffix "_Type" generated. I think this can be closed.

**Comment by schphil** [comment]
@Rawk  I’m still facing this issue, but I might be missing something since I’m still new to ASN.1. See: https://github.com/librasn/rasn/pull/548 - Compile error, point 1.
